version: '3.8'

services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL:sqlite+aiosqlite:///:memory:
      PYTHONPATH: /app

  test:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: pytest tests/
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL:sqlite+aiosqlite:///:memory:
      PYTHONPATH: /app
    depends_on:
      - fastapi

  coverage:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: pytest --cov=app tests/
    volumes:
      - ./app:/app
    environment:
      PYTHONPATH: /app
